package com.indigo.esb.log.db.model;

import java.io.Serializable;
import java.util.Date;

public class TbRecvTlgrHisrKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TB_RECV_TLGR_HISR.TRNSC_ID
     * @mbggenerated  Wed Mar 23 15:05:50 KST 2016
     */
    private String trnscId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TB_RECV_TLGR_HISR.FCLT_ID
     * @mbggenerated  Wed Mar 23 15:05:50 KST 2016
     */
    private String fcltId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TB_RECV_TLGR_HISR.TRNSC_ID
     * @return  the value of TB_RECV_TLGR_HISR.TRNSC_ID
     * @mbggenerated  Wed Mar 23 15:05:50 KST 2016
     */
    public String getTrnscId() {
        return trnscId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TB_RECV_TLGR_HISR.TRNSC_ID
     * @param trnscId  the value for TB_RECV_TLGR_HISR.TRNSC_ID
     * @mbggenerated  Wed Mar 23 15:05:50 KST 2016
     */
    public void setTrnscId( String trnscId ) {
        this.trnscId = trnscId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TB_RECV_TLGR_HISR.FCLT_ID
     * @return  the value of TB_RECV_TLGR_HISR.FCLT_ID
     * @mbggenerated  Wed Mar 23 15:05:50 KST 2016
     */
    public String getFcltId() {
        return fcltId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TB_RECV_TLGR_HISR.FCLT_ID
     * @param fcltId  the value for TB_RECV_TLGR_HISR.FCLT_ID
     * @mbggenerated  Wed Mar 23 15:05:50 KST 2016
     */
    public void setFcltId( String fcltId ) {
        this.fcltId = fcltId;
    }
}